### ISSUE TITLE
Getting responses back

### ISSUE THREAD

**Issue by cayblood** [troupe/restler-q#4]
It looks like you are discarding the second argument of restler's .on() functions. How can I find out what the HTTP response code was? I want to basically use this library to keep looping until I get a 200 response.

**Comment by jloveridge** [comment]
If the status code of the response indicates an error condition, >=400, then the promise will be rejected rather than resolved. As there are other successful response codes I am not quite sure why you would want to loop until you get a 200 specifically. A 206 response code is perfectly acceptable and might be sent by any number of servers.

If you really want the response object though I would suggest you use `.spread`.

**Comment by cayblood** [comment]
Been a while so I can't remember all the of the context, but I do recall that the reason I needed this is because [Python Eve](http://python-eve.org/index.html) REST library returns slightly different response codes for some of its operations depending on the context.

**Comment by jloveridge** [comment]
Then you should definitely use `.spread` instead of `.then` so you can get the actual response object as well. There is an example in the README.

**Comment by cayblood** [comment]
Sounds good. Thanks for the info.
